name: Code checks
on: [push, workflow_dispatch]

jobs:
  code_checks:
    name: Code checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-dependencies
      - name: Typecheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint
